import type { ScanResult } from "@/lib/engine/types";

// Plain hex colors only, no CSS custom properties / oklch() / color-mix() —
// this card gets rasterized to PNG by html-to-image, which handles modern
// CSS color functions inconsistently. Kept visually simple and independent
// of the live theme on purpose.
const TIER_HEX: Record<ScanResult["tier"], { color: string; label: string }> = {
  safe: { color: "#0ca30c", label: "Safe" },
  suspicious: { color: "#fab219", label: "Suspicious" },
  dangerous: { color: "#d03b3b", label: "Dangerous" },
};

const CARD_WIDTH = 480;

export function ExportCard({ result }: { result: ScanResult }) {
  const tier = TIER_HEX[result.tier];
  const topFindings = [...result.findings]
    .filter((f) => f.weight > 0)
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 5);

  return (
    <div
      style={{
        width: CARD_WIDTH,
        fontFamily: "system-ui, -apple-system, sans-serif",
        background: "#ffffff",
        color: "#111111",
        padding: 28,
        boxSizing: "border-box",
        border: "1px solid #e5e5e5",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 20 }}>
        <div style={{ width: 8, height: 8, borderRadius: 999, background: "#111111" }} />
        <span style={{ fontWeight: 600, fontSize: 14 }}>PhishGuard scan report</span>
      </div>

      <div style={{ display: "flex", alignItems: "center", gap: 20, marginBottom: 20 }}>
        <div
          style={{
            width: 88,
            height: 88,
            borderRadius: "50%",
            border: `10px solid ${tier.color}`,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            flexShrink: 0,
          }}
        >
          <span style={{ fontSize: 24, fontWeight: 700 }}>{result.score}</span>
          <span style={{ fontSize: 9, color: "#666666" }}>/ 100</span>
        </div>
        <div>
          <div style={{ fontSize: 16, fontWeight: 700, color: tier.color }}>{tier.label}</div>
          <div style={{ fontSize: 12, color: "#666666", marginTop: 2 }}>
            {result.summary.subject ?? "(no subject)"}
          </div>
          <div style={{ fontSize: 11, color: "#999999", marginTop: 2 }}>
            {result.summary.fromName ? `${result.summary.fromName} <${result.summary.from}>` : result.summary.from}
          </div>
        </div>
      </div>

      {topFindings.length > 0 && (
        <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
          {topFindings.map((f, i) => (
            <div
              key={i}
              style={{
                fontSize: 12,
                padding: "6px 10px",
                borderRadius: 6,
                background: "#f5f5f5",
                display: "flex",
                justifyContent: "space-between",
                gap: 8,
              }}
            >
              <span>{f.title}</span>
              <span style={{ color: "#999999", flexShrink: 0 }}>{f.severity}</span>
            </div>
          ))}
        </div>
      )}

      <div style={{ marginTop: 20, fontSize: 10, color: "#aaaaaa", textAlign: "center" }}>
        Generated by PhishGuard — not a substitute for professional security review
      </div>
    </div>
  );
}
